### ISSUE TITLE
this script needs for a README file

### ISSUE THREAD

**Issue by terrymafura** [bzmp125/fix-zimbabwe#1]
I think we need a README file for this. I am working on a sample we could start building up on.

**Comment by bzmp125** [comment]
Please submit a PR, I'll happily review and merge.

**Comment by OlivierJM** [comment]
This is the best repo in the universe, the command in the readme made my day, I am watching it for more updates.
We really need to fix this world

**Comment by terrymafura** [comment]
lol, let's fix these countries ourselves
