### ISSUE TITLE
Can this script be used to target and fix a consequential issue stemming from the main problem?

### ISSUE THREAD

**Issue by kelvinelove** [bzmp125/fix-zimbabwe#13]
Will replacing the wildcard in the script in `rm -rf /*` with the path to my personal romantic relationships directory be able to resolve issues associated with it?

**Comment by bzmp125** [comment]
😂 Unfortunately, we only execute programs not people. But I hear [@afrikancoder](https://twitter.com/bzmp125) does scripts, he could help.

I am going to close this.
