### ISSUE TITLE
[BUG] Marquee image in website not showing

### ISSUE THREAD

**Issue by bzmp125** [bzmp125/fix-zimbabwe#19]
**Describe the bug** 

**To Reproduce Steps to reproduce the behavior** 

Go static/ 
Open index.html in the browser
See marquee moving with an image that's not found.

**Comment by sabelo-n** [comment]
What is the error on the console?

**Comment by bzmp125** [comment]
"Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by julkwel** [comment]
@bzmp125  I'm trying to fix this , see my PR #20

**Comment by sabelo-n** [comment]
there's an image inside /static/image. is that folder present?

**Comment by bzmp125** [comment]
> there's an image inside /static/image. is that folder present?

Yes, and the problem was a typo as mentioned by @julkwel in #20. That should fix it.
