### ISSUE TITLE
add contributors using the bot

### ISSUE THREAD

**Issue by OlivierJM** [bzmp125/fix-zimbabwe#5]
The @allcontributors can be used to auto-add contributors of any kind to the readme

This is good one https://allcontributors.org

**Comment by terrymafura** [comment]
this is cool. I've been manually adding on most repos

**Comment by bzmp125** [comment]
😭 I was just googling for this to add you @OlivierJM . Thank you very much. Adding the bot now.

**Comment by OlivierJM** [comment]
It is super helpful and easy to use, I use it on my repos.

**Comment by bzmp125** [comment]
@all-contributors please add @OlivierJM for maintenance

**Comment by bzmp125** [comment]
@all-contributors please add @OlivierJM for maintenance

**Comment by bzmp125** [comment]
@all-contributors please add @OlivierJM for maintenance

**Comment by bzmp125** [comment]
@all-contributors please add @maffsojah for documentation, maintenance

**Comment by bzmp125** [comment]
@all-contributors please add @sabelo-n for documentation

**Comment by bzmp125** [comment]
I seem to be messing it up 😆

**Comment by bzmp125** [comment]
@all-contributors please add @OlivierJM for maintenance

**Comment by terrymafura** [comment]
I've noticed some merging issues with the readme

**Comment by bzmp125** [comment]
@all-contributors please add @OlivierJM for maintenance

**Comment by bzmp125** [comment]
I think I finally got the hang of it. Thanks again @OlivierJM

**Comment by bzmp125** [comment]
> I've noticed some merging issues with the readme

Yeah, I'll blame the training wheels.
